package pl.volleylove.antenka.enums;

public enum SignUpInfo {
    OK, COMPLETE_PLAYER_OR_TEAM_PROFILE, YOU_DO_NOT_MEET_EVENT_REQ, INCORRECT_EVENT_ID_OR_SLOT_NUM,
    SLOT_HAS_PLAYER_ALREADY, EVENT_IS_CLOSED, YOU_ARE_SINGED_UP_FOR_THIS_EVENT
}
